{% set name = "xtensor-io" %}
{% set version = "0.5.0" %}
{% set sha256 = "931a5696449f94a934fe2790c20ffc6a298131e8b164d766622eedb7fb31a051" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor-io/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    # - {{ compiler('cxx') }}
    - toolchain
    - gcc-7  # [linux]
    - cmake
    - openimageio
    - zlib
    - xtensor
    - libsndfile  # [not win]
    - boost  # need to add boost here to grab the latest version necessary for openimageio
  run:
    - zlib
    - xtensor
    - openimageio
    - boost
    - libsndfile  # [not win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image/NPZ input/output for xtensor, the C++ tensor algebra library
  description: This library enables loading of many image formats into xtensor/xarrays and NPZ.
  doc_url: http://xtensor-io.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-io

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
